// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpUbdKWceV-MvSR0zFBYweDZR83gnGXfU',
    appId: '1:663048927877:web:8234595a0506ad6518c7ec',
    messagingSenderId: '663048927877',
    projectId: 'schoolapp-a444b',
    authDomain: 'schoolapp-a444b.firebaseapp.com',
    storageBucket: 'schoolapp-a444b.appspot.com',
    measurementId: 'G-7YRFWQCJR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByv_5Ne_58Y_PRJ7psJlmR0XeRDdi5kRo',
    appId: '1:663048927877:android:6adb7c8156c28dfa18c7ec',
    messagingSenderId: '663048927877',
    projectId: 'schoolapp-a444b',
    storageBucket: 'schoolapp-a444b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoNgx2JC4bon3-KhVZqvwkGvZmFIR2vgg',
    appId: '1:663048927877:ios:cd59259429784eb118c7ec',
    messagingSenderId: '663048927877',
    projectId: 'schoolapp-a444b',
    storageBucket: 'schoolapp-a444b.appspot.com',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoNgx2JC4bon3-KhVZqvwkGvZmFIR2vgg',
    appId: '1:663048927877:ios:e9a5469f494219f118c7ec',
    messagingSenderId: '663048927877',
    projectId: 'schoolapp-a444b',
    storageBucket: 'schoolapp-a444b.appspot.com',
    iosBundleId: 'com.example.schoolApp.RunnerTests',
  );
}
